import { type NextPage } from "next";
import Head from "next/head";

import {
  ArticleCard,
  NavBar,
  PageBanner,
  Spinner,
  TabsList,
} from "~/components";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blogs | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Blogs"
        description="Explore latest articles written moroccan tech community"
      />
      <main className="flex flex-1 flex-col items-center justify-center px-20 text-center">
        <TabsList
          routes={[
            { name: "Blogs", link: "/blog" },
            { name: "feed", link: "/blog/feed" },
          ]}
          activeIndex={1}
        />
        <Feed />
      </main>
    </>
  );
};

export default Home;

const Feed: React.FC = () => {
  const { data, isLoading } = api.blog.articles.useQuery();

  if (isLoading) {
    return <Spinner />;
  }

  return (
    <section className="w-screen py-20">
      <div className="mx-auto grid max-w-screen-lg grid-cols-1 gap-5 p-5 sm:grid-cols-2 md:grid-cols-3 lg:gap-10">
        {data?.map((post) => (
          <ArticleCard key={post.id} {...post} />
        ))}
      </div>
    </section>
  );
};
