import { type NextPage } from "next";
import Head from "next/head";

import { NavBar, PageBanner, TabsList } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blogs | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Blogs"
        description="Explore latest articles written moroccan tech community"
      />
      <main className="flex flex-1 flex-col items-center justify-center px-20 text-center">
        <TabsList
          routes={[
            { name: "Blogs", link: "/blog" },
            { name: "feed", link: "/blog/feed" },
          ]}
          activeIndex={1}
        />
        <Feed />
      </main>
    </>
  );
};

export default Home;

const Feed: React.FC = () => {
  return (
    <div className="grid gap-4 sm:grid-cols-2 sm:gap-8 lg:grid-cols-2 xl:grid-cols-2 xl:gap-8">
      feed
    </div>
  );
};
