import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { NavBar, PageBanner, TabsList } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blogs | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Blogs"
        description="Explore latest articles written moroccan tech community"
      />
      <main className="flex flex-1 flex-col items-center justify-center px-20 text-center">
        <TabsList
          routes={[
            { name: "Blogs", link: "/blog" },
            { name: "feed", link: "/blog/feed" },
          ]}
          activeIndex={0}
        />
        <Blogs />
      </main>
    </>
  );
};

export default Home;

const Blogs: React.FC = () => {
  const { data, isLoading } = api.blog.blogs.useQuery();

  if (isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <section className="w-screen py-20">
      <div className="mx-auto grid max-w-screen-lg grid-cols-1 gap-5 p-5 sm:grid-cols-2 md:grid-cols-3 lg:gap-10">
        {data?.map((blog) => (
          <Article
            key={blog.id}
            title={blog.title}
            description={blog.description}
            image={blog.image}
          />
        ))}
      </div>
    </section>
  );
};

type ArticleProps = {
  title: string;
  description: string;
  image: string;
};
const Article = ({ title, description, image }: ArticleProps) => {
  return (
    <div className="group relative m-10 h-60 w-full  cursor-pointer overflow-hidden rounded-lg shadow-md">
      <div className="absolute left-0 top-0 h-full w-full  transition-all duration-300 ease-in-out group-hover:-top-96">
        <img
          className="h-4/6 w-full object-cover"
          src={image}
          alt={`${title} website image`}
        />
        <div className="flex h-2/6 items-center justify-center  ">
          <h1 className=" px-4 text-center font-serif text-xl font-semibold">
            {title}
          </h1>
        </div>
      </div>

      <div className="absolute left-0 -bottom-96 flex h-full w-full flex-col justify-center transition-all duration-300 ease-in-out group-hover:bottom-0">
        <h1 className="mb-2 px-8 text-center font-serif text-xl font-semibold ">
          {title}
        </h1>
        <p className="px-8 text-center">{description}</p>
      </div>
    </div>
  );
};
