import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { DashboardLayout, NavBar, OSProjectCard } from "~/components";
import { api } from "~/utils/api";

const Dashboard: NextPage = () => {
  const { data } = useSession();
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <DashboardLayout activePage="Home">
        <div className="pt-4">
          <h1 className="py-2 text-2xl font-semibold">
            Welcome {data?.user.name}{" "}
          </h1>
        </div>
        <hr className="mt-4 mb-8" />
        <p> show option here </p>
      </DashboardLayout>
    </>
  );
};

export default Dashboard;
