import { type NextPage } from "next";
import Head from "next/head";
import { DashboardLayout, NavBar, OSProjectCard } from "~/components";
import { api } from "~/utils/api";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <DashboardLayout activePage="Home">
        <Repos />
      </DashboardLayout>
    </>
  );
};

export default Dashboard;

const Repos: React.FC = () => {
  const { data, isLoading } = api.github.repos.useQuery();

  if (isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl">
        {data?.length} open source projects
        {data?.map((repo) => (
          <OSProjectCard key={repo.id} project={repo} />
        ))}
      </p>
    </div>
  );
};
