import { type NextPage } from "next";
import Head from "next/head";
import { DashboardLayout, NavBar } from "~/components";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>podcasts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <DashboardLayout activePage="Podcasts">
        <div> podcasts</div>
      </DashboardLayout>
    </>
  );
};

export default Index;
