import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

import UpperBanner from "../../components/UpperBanner";
import Navbar from "../../components/Navbar";
import Header from "../../components/Header";

import CommunitiesCards from "../../components/CommunitiesCards";

export default function Communities() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Communities - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <div className={styles.main}>
        <UpperBanner />
        <Navbar currentPageTitle={false} />
        <Header
          headerTitle={"Communities"}
          haederDescription={
            "Check out the best developers at your domain and book a session of mentoring How does it work?"
          }
        />
        <CommunitiesCards />
      </div>
    </div>
  );
}
