import { type NextPage } from "next";
import Head from "next/head";
import { NavBar, PageBanner } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Home"
        description="Explore latest innovations in the Tech world New here? Check our Tutorial on Open Source"
      />
      <main className="mx-auto flex  max-w-screen-lg flex-1 flex-col items-center justify-center px-20 text-center ">
        home page here
      </main>
    </>
  );
};

export default Home;
