import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { NavBar, OSProjectCard, PageBanner, TabsList } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Open Source | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Home"
        description="Explore latest innovations in the Tech world New here? Check our Tutorial on Open Source"
      />
      <main className="mx-auto flex  max-w-screen-lg flex-1 flex-col items-center justify-center px-20 text-center  ">
        <TabsList
          routes={[
            { name: "Open Source", link: "/open-source" },
            { name: "ranking", link: "/open-source/ranking" },
          ]}
          activeIndex={0}
        />
        <Repos />
      </main>
    </>
  );
};

export default Home;

const Repos: React.FC = () => {
  const { data, isLoading } = api.github.repos.useQuery();

  if (isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <div className="flex flex-row flex-wrap items-center justify-center">
      {data?.map((repo) => (
        <OSProjectCard key={repo.id} project={repo} />
      ))}
    </div>
  );
};
