import React, { useState } from "react";
import Head from "next/head";

import Header from "../../components/Header";

import PodcastsFilterBar from "../../components/PodcastsFilterBar";
import PodcastsCard from "../../components/PodcastsCard";
import PodcastRadio from "../../components/PodcastsRadio";
import { getParsedYAML } from "../../services/parser";

export default function Podcasts({ data }) {
  const [filterOpen, setFilterOpen] = useState(false);
  const [podcastContent, setPodcastContent] = useState("PODCASTS");

  return (
    <>
      <Head>
        <title>Podcasts - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <Header
        headerTitle={"Podcasts"}
        haederDescription={"Find your favorite Moroccan Podcasts"}
      />

      <div className="mainContainer">
        <PodcastsFilterBar
          filterOpen={filterOpen}
          setFilterOpen={setFilterOpen}
          podcastContent={podcastContent}
          setPodcastContent={setPodcastContent}
        />
        {podcastContent == "PODCASTS" ? (
          <PodcastsCard podcasts={data} />
        ) : podcastContent == "RADIO" ? (
          <PodcastRadio />
        ) : null}
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const { data } = await getParsedYAML("podcasts.yaml");
  return {
    props: { data },
  };
};
