const data = [
  {
    id: 1,
    avatar: "/avatars/avatar_1.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "Obytes",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 2,
    avatar: "/avatars/avatar_2.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "X-HUB",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 3,
    avatar: "/avatars/avatar_1.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "Obytes",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 4,
    avatar: "/avatars/avatar_2.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "X-HUB",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 5,
    avatar: "/avatars/avatar_1.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "Obytes",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 6,
    avatar: "/avatars/avatar_2.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "X-HUB",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
  {
    id: 7,
    avatar: "/avatars/avatar_1.png",
    name: "Salman El Yagoubi",
    username: "salmyagoubi",
    company: "Obytes",
    location: "	Rabat, Morocco",
    topRepos: "Awesome-Morocco",
    contributions: 1932,
  },
];

export default data;
