import React, { useState } from "react";
import Head from "next/head";

import Header from "../../components/Header";
import MentorsCards from "../../components/MentorsCards";

import { getParsedYAML } from "../../services/parser";

export default function Mentors({ data }) {
  return (
    <>
      <Head>
        <title>Mentors - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <Header
        headerTitle={"Mentors"}
        haederDescription={
          "Check out the best developers at your domain and book a session of mentoring, How does it work?"
        }
      />

      <div className="mainContainer">
        <MentorsCards mentors={data} />
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const { data } = await getParsedYAML("mentors.yaml");
  return {
    props: { data },
  };
};
