import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

import UpperBanner from "../../components/UpperBanner";
import Navbar from "../../components/Navbar";
import Header from "../../components/Header";
import MentorsCards from "../../components/MentorsCards";

import { getParsedYAML } from "../../services/parser";

export default function Mentors({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mentors - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <div className={styles.main}>
   
        <Header
          headerTitle={"Mentors"}
          haederDescription={
            "Check out the best developers at your domain and book a session of mentoring, How does it work?"
          }
        />
        <MentorsCards mentors={data} />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const { data } = await getParsedYAML("mentors.yaml");
  return {
    props: { data },
  };
};
