import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/Blogs.module.css";

import UpperBanner from "../../components/UpperBanner";
import Navbar from "../../components/Navbar";
import Header from "../../components/Header";
import BlogsFilterBar from "../../components/BlogsFilterBar";

import BlogsFeed from "../../components/BlogsFeed";
import BlogsOrgs from "../../components/BlogsOrgs";
import BlogsAuthors from "../../components/BlogsAuthors";

export default function Blogs() {
  const [filterOpen, setFilterOpen] = useState(false);
  const [blogsContent, setBlogsContent] = useState("FEED");

  return (
    <div className={styles.container}>
      <Head>
        <title>Blogs - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <div>
        <UpperBanner />
        <Navbar />
        <Header
          headerTitle={"Blogs"}
          haederDescription={
            "Read the latest articles written by Moroccan developers Never written a blog before? Check our tutorial"
          }
        />
        <BlogsFilterBar
          filterOpen={filterOpen}
          setFilterOpen={setFilterOpen}
          blogsContent={blogsContent}
          setBlogsContent={setBlogsContent}
        />
        <div>
          {blogsContent == "FEED" ? (
            <BlogsFeed />
          ) : blogsContent == "ORGANIZATIONS" ? (
            <BlogsOrgs />
          ) : blogsContent == "AUTHORS" ? (
            <BlogsAuthors />
          ) : null}
        </div>
      </div>
    </div>
  );
}
