import React, { useState } from "react";
import Head from "next/head";

import Header from "../../components/Header";

import BlogsFilterBar from "../../components/BlogsFilterBar";
import BlogsFeed from "../../components/BlogsFeed";
import BlogsOrgs from "../../components/BlogsOrgs";
import BlogsAuthors from "../../components/BlogsAuthors";
import { getParsedYAML } from "../../services/parser";

export default function Blogs({ data }) {
  const [filterOpen, setFilterOpen] = useState(false);
  const [blogsContent, setBlogsContent] = useState("FEED");

  return (
    <>
      <Head>
        <title>Blogs - Awesome Morocco UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/site-icon.svg" />
      </Head>

      <Header
        headerTitle={"Blogs"}
        haederDescription={
          "Read the latest articles written by Moroccan developers Never written a blog before? Check our tutorial"
        }
      />
      <div className="mainContainer">
        <BlogsFilterBar
          filterOpen={filterOpen}
          setFilterOpen={setFilterOpen}
          blogsContent={blogsContent}
          setBlogsContent={setBlogsContent}
        />
        <div>
          {blogsContent == "FEED" ? (
            <BlogsFeed feeds={data} />
          ) : blogsContent == "ORGANIZATIONS" ? (
            <BlogsOrgs orgs={data} />
          ) : blogsContent == "AUTHORS" ? (
            <BlogsAuthors />
          ) : null}
        </div>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const { data } = await getParsedYAML("blogs.yaml");
  return {
    props: { data },
  };
};
