@_default:
    just --list

@alex:
	npx alex readme.md

@build:
    just toc
    bundle exec jekyll build

@lint:
    -curlylint _layouts/
    -npx awesome-lint readme.md

@serve:
    modd --file=modd.conf
    bundle exec jekyll serve --drafts --watch --port 8000

@toc:
	npx doctoc readme.md
