// Generated by Xata Codegen 0.26.9. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "os_repositories",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "url", type: "string", unique: true },
      { name: "owner", type: "string" },
      { name: "stars", type: "int" },
      { name: "forks", type: "int" },
      { name: "issues", type: "int" },
      { name: "language", type: "string" },
      { name: "topics", type: "multiple" },
      {
        name: "submitted_by",
        type: "string",
        notNull: true,
        defaultValue: "anonymous",
      },
      { name: "draft", type: "bool", defaultValue: "true" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type OsRepositories = InferredTypes["os_repositories"];
export type OsRepositoriesRecord = OsRepositories & XataRecord;

export type DatabaseSchema = {
  os_repositories: OsRepositoriesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Youssouf-EL-AZIZI-s-workspace-28d54f.eu-west-1.xata.sh/db/aw-morocco",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
