import { type NextPage } from "next";
import Head from "next/head";

import { NavBar, OsRankingTable, PageBanner, TabsList } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Open Source | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Open Source"
        description="Explore latest innovations in the Tech world New here? Check our Tutorial on Open Source"
      />
      <main className="mx-auto flex  max-w-screen-lg flex-col items-center justify-center  text-center  ">
        <TabsList
          routes={[
            { name: "Open Source", link: "/open-source" },
            { name: "ranking", link: "/open-source/ranking" },
            {
              name: "First Contribution",
              link: "/open-source/first-contribution",
            },
          ]}
          activeIndex={1}
        />
        <OsRankingTable />
      </main>
    </>
  );
};

export default Home;
