import { type NextPage } from "next";
import Head from "next/head";
import { Heading } from "~/components/podcasts/heading";

import { api } from "~/utils/api";
import { NavBar, PageBanner } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Podcast | Awesome Morocco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <PageBanner
        title="Podcasts"
        description="Explore latest innovations in the Tech world New here? Check our Podcast"
      />
      <main className="flex flex-1 flex-col items-center justify-center text-center">
        <Heading />
        <Podcasts />
      </main>
    </>
  );
};

export default Home;

const Podcasts: React.FC = () => {
  const { data, isLoading } = api.podcast.all.useQuery();

  if (isLoading) {
    return(
      <div className="w-12 h-12 rounded-full animate-spin border-2 border-dashed border-blue-500 border-t-transparent"></div>
    )
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 sm:gap-8 lg:grid-cols-2 xl:grid-cols-2 xl:gap-8">
      {data?.map((podcast) => (
        <div key={podcast.id}>
          <span> Podcast URL : {podcast.source} </span>
          
        </div>
      ))}
    </div>
  );
};
